[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mess = "MESS6sYCuTxwEZsF8M6zrkBdUd4oNvqWCdyBTx6KFNo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "mess-wallet.json"

[scripts]
test = "bun test --timeout 1000000"
