name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        working-directory: app
        run: bun install

      - name: Build the project
        working-directory: app
        env:
          VITE_RPC_URL: ${{ secrets.VITE_RPC_URL }}
          VITE_RPC_CLUSTER: ${{ secrets.VITE_RPC_CLUSTER }}
          VITE_ADDRESS_LOOKUP_TABLE: ${{ secrets.VITE_ADDRESS_LOOKUP_TABLE }}
          VITE_MESS_PROGRAM_ID: ${{ secrets.VITE_MESS_PROGRAM_ID }}
          DIALECT_SDK_CREDENTIALS: ${{ secrets.DIALECT_SDK_CREDENTIALS }}
        run: bun run build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add -f app/dist
          git commit -m "Deploy to gh-pages"
          git push --force origin `git subtree split --prefix app/dist HEAD`:refs/heads/gh-pages

      - name: Cache Bun dependencies
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-
